version: '3'
services:
  load-tester:
    image: jirapus/did-tendermint:loadtest-abci-create-request
    environment:
      - DURATION=${DURATION}
      - TXPERSEC=${TXPERSEC}
      - WS_CONNECTION=${WS_CONNECTION:-10}
    entrypoint: npm
    command:
      - start
    networks:
      - ndidplatform

networks:
  ndidplatform:
