{
 "title": "Tendermint",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Block Processing Time (Last 5 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tendermint_state_block_processing_time_sum[5m])/rate(tendermint_state_block_processing_time_count[5m])"
    }
   ]
  },
  {
   "title": "Average Block Processing Time (Last 1 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(tendermint_state_block_processing_time_sum[1m])/rate(tendermint_state_block_processing_time_count[1m])"
    }
   ]
  },
  {
   "title": "Tx Size (Last 5 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tendermint_mempool_tx_size_bytes_sum[5m]) / rate(tendermint_mempool_tx_size_bytes_count[5m])"
    }
   ]
  },
  {
   "title": "Average Tx Size (Last 5 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(tendermint_mempool_tx_size_bytes_sum[5m]) / rate(tendermint_mempool_tx_size_bytes_count[5m])"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tendermint_mempool_size" }
   ]
  },
  {
   "title": "Consensus Rounds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tendermint_consensus_rounds" }
   ]
  },
  {
   "title": "Total Txs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tendermint_consensus_total_txs" }
   ]
  },
  {
   "title": "Consensus Height",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "tendermint_consensus_height" }
   ]
  },
  {
   "title": "Number of transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tendermint_consensus_num_txs" }
   ]
  },
  {
   "title": "Consensus Block Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes"
    }
   ]
  },
  {
   "title": "Average Consensus Tx Rate (Last 1 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "Tx/s" }
   ],
   "targets": [
    {
     "expr": "rate(tendermint_consensus_total_txs[1m])"
    }
   ]
  },
  {
   "title": "Average Consensus Block Rate (Last 5 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short", "label": "Blocks/s" }
   ],
   "targets": [
    {
     "expr": "rate(tendermint_consensus_height[5m])"
    }
   ]
  },
  {
   "title": "Consensus Block Interval",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds"
    }
   ]
  },
  {
   "title": "Consensus Missing Validator",
   "type": "graph",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators"
    }
   ]
  },
  {
   "title": "P2P Peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tendermint_p2p_peers" }
   ]
  },
  {
   "title": "Average Consensus Txs per Block (Last 5 min)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tendermint_consensus_total_txs[5m]) / rate(tendermint_consensus_height[5m])"
    }
   ]
  }
 ]
}