version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.6.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
     - '--web.enable-admin-api'
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:5.4.2
    volumes: 
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - "3000:3000"